//se utilizan tanto en el action como en el reducer
//sirve para describir que es lo que pasa en tu aplicacion
            //variable                String
            //   ↓                      ↓
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const COMENZAR_DESCARGA_USUARIOS = 'COMENZAR_DESCARGA_USUARIOS';
export const DESCARGA_USUARIOS_EXITO = 'DESCARGA_USUARIOS_EXITO';
export const DESCARGA_USUARIOS_ERROR = 'DESCARGA_USUARIOS_ERROR';

export const OBTENER_USUARIO_ELIMINAR = 'OBTENER_USUARIO_ELIMINAR';
export const USUARIO_ELIMINADO_EXITO = 'USUARIO_ELIMINADO_EXITO';
export const USUARIO_ELIMINADO_ERROR = 'USUARIO_ELIMINADO_ERROR';

export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';
export const COMENZAR_EDICION_USUARIO = 'COMENZAR_EDICION_USUARIO'
export const USUARIO_EDITAR_EXITO = 'USUARIO_EDITAR_EXITO';
export const USUARIO_EDITAR_ERROR = 'USUARIO_EDITAR_ERROR';
//partido
export const AGREGAR_PARTIDO = 'AGREGAR_PARTIDO';
export const AGREGAR_PARTIDO_EXITO = 'AGREGAR_PARTIDO_EXITO';
export const AGREGAR_PARTIDO_ERROR = 'AGREGAR_PARTIDO_ERROR';

export const COMENZAR_DESCARGA_PARTIDOS = 'COMENZAR_DESCARGA_PARTIDOS';
export const DESCARGA_PARTIDOS_EXITO = 'DESCARGA_PARTIDOS_EXITO';
export const DESCARGA_PARTIDOS_ERROR = 'DESCARGA_PARTIDOS_ERROR';

export const OBTENER_PARTIDO_ELIMINAR = 'OBTENER_PARTIDO_ELIMINAR';
export const PARTIDO_ELIMINADO_EXITO = 'PARTIDO_ELIMINADO_EXITO';
export const PARTIDO_ELIMINADO_ERROR = 'PARTIDO_ELIMINADO_ERROR';

export const OBTENER_PARTIDO_EDITAR = 'OBTENER_PARTIDO_EDITAR';
export const COMENZAR_EDICION_PARTIDO = 'COMENZAR_EDICION_PARTIDO'
export const PARTIDO_EDITAR_EXITO = 'PARTIDO_EDITAR_EXITO';
export const PARTIDO_EDITAR_ERROR = 'PARTIDO_EDITAR_ERROR';
//estadisticas
export const AGREGAR_ESTADISTICA = 'AGREGAR_ESTADISTICA';
export const AGREGAR_ESTADISTICA_EXITO = 'AGREGAR_ESTADISTICA_EXITO';
export const AGREGAR_ESTADISTICA_ERROR = 'AGREGAR_ESTADISTICA_ERROR';

export const COMENZAR_DESCARGA_ESTADISTICAS = 'COMENZAR_DESCARGA_ESTADISTICAS';
export const DESCARGA_ESTADISTICAS_EXITO = ' DESCARGA_ESTADISTICAS_EXITO';
export const DESCARGA_ESTADISTICAS_ERROR = 'DESCARGA_ESTADISTICAS_ERROR';

export const OBTENER_ESTADISTICA_ELIMINAR = 'OBTENER_ESTADISTICA_ELIMINAR';
export const ESTADISTICA_ELIMINADO_EXITO = 'ESTADISTICA_ELIMINADO_EXITO';
export const ESTADISTICA_ELIMINADO_ERROR = 'ESTADISTICA_ELIMINADO_ERROR';

export const OBTENER_ESTADISTICA_EDITAR = 'OBTENER_ESTADISTICA_EDITAR';
export const COMENZAR_EDICION_ESTADISTICA = 'COMENZAR_EDICION_ESTADISTICA'
export const ESTADISTICA_EDITAR_EXITO = 'ESTADISTICA_EDITAR_EXITO';
export const ESTADISTICA_EDITAR_ERROR = 'ESTADISTICA_EDITAR_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const INICIAR_SESION = 'INICIAR_SESION'
export const INICIAR_ERROR = 'INICIAR_ERROR'

export const INICIANDO_COOKIE = 'INICIANDO_COOKIE'
export const ELIMINANDO_COOKIE = 'ELIMINANDO_COOKIE'
export const CERRAR_SESION = 'CERRAR_SESION'

